name = "linear-tools"
main = "src/index.ts"
compatibility_date = "2024-03-20"

[vars]
LINEAR_API_KEY = ""
MANAGER_BOT_API_KEY = ""
BUG_BOT_API_KEY = ""
FEATURE_BOT_API_KEY = ""
IMPROVEMENT_BOT_API_KEY = ""
